language: php

php:
    - 7.1

before_script:
    - sudo apt-get install -y pkg-config zlib1g-dev libmemcached-dev
    - printf "no --disable-memcached-sasl\n" | pecl install memcached
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
